version: '3.8'

services:
  web:
    build: .
    container_name: pofuai-web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - DATABASE_URL=mysql://root:password@db:3306/pofuai
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./storage:/app/storage
      - ./public/uploads:/app/public/uploads
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - pofuai-network

  db:
    image: mysql:8.0
    container_name: pofuai-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pofuai
      - MYSQL_USER=pofuai
      - MYSQL_PASSWORD=pofuai_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./core/Database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    restart: unless-stopped
    networks:
      - pofuai-network

  redis:
    image: redis:7-alpine
    container_name: pofuai-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - pofuai-network

  nginx:
    image: nginx:alpine
    container_name: pofuai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public/static:/usr/share/nginx/html/static
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - pofuai-network

volumes:
  mysql_data:
  redis_data:

networks:
  pofuai-network:
    driver: bridge